export const START_SIGNIN = "START_SIGNIN";
export const COMPLETE_SIGNIN = "COMPLETE_SIGNIN";
export const ERROR_SIGNIN = "ERROR_SIGNIN";

export const START_SIGNUP = "START_SIGNUP";
export const COMPLETE_SIGNUP = "COMPLETE_SIGNUP";
export const ERROR_SIGNUP = "ERROR_SIGNUP";

export const START_SIGNOUT = "SIGNOUT";
export const COMPLETE_SIGNOUT = "COMPLETE_SIGNOUT";
export const ERROR_SIGNOUT = "ERROR_SIGNOUT";

export const START_CREATE_CATEGORY = "START_CREATE_CATEGORY";
export const COMPLETE_CREATE_CATEGORY = "COMPLETE_CREATE_CATEGORY";
export const ERROR_CREATE_CATEGORY = "ERROR_CREATE_CATEGORY";
