export const START_SIGNIN = "START_SIGNIN";
export const COMPLETE_SIGNIN = "COMPLETE_SIGNIN";
export const ERROR_SIGNIN = "ERROR_SIGNIN";
export const AUTHENTICATESTORAGE = "AUTHENTICATESTORAGE";

export const START_SIGNUP = "START_SIGNUP";
export const COMPLETE_SIGNUP = "COMPLETE_SIGNUP";
export const ERROR_SIGNUP = "ERROR_SIGNUP";

export const START_LOGOUT = "LOGOUT";
export const COMPLETE_LOGOUT = "COMPLETE_LOGOUT";
export const ERROR_LOGOUT = "ERROR_LOGOUT";
